name: Fetch Blogger Stats

on:
  schedule:
    - cron: '*/30 * * * *' # 每 30 分钟执行一次
  workflow_dispatch:       # 支持手动触发

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Blogger stats
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: python fetch_stats.py

      - name: Commit & Push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/stats.json
          git diff --cached --quiet || git commit -m "Update stats.json [CI]"
          git push